/**
 * Fix MDX-incompatible <details> blocks generated by the tabs transformer.
 * Ensures blank lines around block content inside <details> so MDX parses correctly.
 */
import { readFile, writeFile, readdir } from 'fs/promises';
import { join } from 'path';

const DOCS = new URL('../src/content/docs', import.meta.url).pathname;

async function walk(dir) {
  const files = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) files.push(...(await walk(p)));
    else if (e.name.endsWith('.mdx')) files.push(p);
  }
  return files;
}

function fix(content) {
  // Ensure blank line after <summary>...</summary> inside <details>
  content = content.replace(
    /(<details><summary>[^<]*<\/summary>)(\n)([^\n])/g,
    '$1\n\n$3'
  );
  // Ensure blank line before </details>
  content = content.replace(/([^\n])\n(<\/details>)/g, '$1\n\n$2');
  // Ensure blank line after </details> if followed by content
  content = content.replace(/(<\/details>)\n([^\n<])/g, '$1\n\n$2');
  // Ensure blank line before </div> that closes tabs-container
  content = content.replace(/(<\/details>)\n(<\/div>)/g, '$1\n\n$2');
  return content;
}

async function main() {
  const files = await walk(DOCS);
  let fixed = 0;
  for (const file of files) {
    const raw = await readFile(file, 'utf-8');
    if (!raw.includes('<details>')) continue;
    const updated = fix(raw);
    if (updated !== raw) {
      await writeFile(file, updated, 'utf-8');
      fixed++;
    }
  }
  console.log(`✅ Fixed tabs/details in ${fixed} files`);
}

main().catch(console.error);
